@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

A --> b : 你觉得呢

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml